metadata:
  author: Arcane Cyber, LLC
  copyright: Copyright 2025

product:
  name: RedaQt
  major_version: 2
  minor_version: 1
  patch_version: 0
  extension: epf

crypto_config:
  encryption_algorithm: aes
  encryption_key_length: 256
  encryption_mode: gcm
  hash_algorithm: sha512