default_settings:
  appearance: dark
  certificate:
    add_certificate: true
    location: data/My_logo.jpg
  mfa:
    methods:
      bio: false
      hardware_key: false
      pin: false
      totp: false
    mfa_active: false
  request_receipt:
    on_delivery: false
    on_request: false
  smart_policy:
    methods:
      do_not_open_after: false
      do_not_open_before: false
      lock_to_user: false
      no_policy: true
      open_with_keyword: false
      passphrase: false
